<?php
return array (
  25 => 
  array (
    'id' => '25',
    'catid' => '6',
    'typeid' => '0',
    'title' => 'interesting',
    'style' => '',
    'thumb' => 'https://timgsa.baidu.com/timg?image&amp;quality=80&amp;size=b9999_10000&amp;sec=1547894296573&amp;di',
    'keywords' => 'interesting',
    'description' => '华理MBA2019年入学网报时间为10月10日-10月31日，每天9：00-22：00。华理MBA网报攻略口袋版，轻松理清MBA报考流程，送给各位挑灯夜读奋力冲   ',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=6&id=25',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1540373531',
    'updatetime' => '1540378367',
    'hitsid' => 'c-1-25',
    'views' => '16',
    'yesterdayviews' => '0',
    'dayviews' => '16',
    'weekviews' => '16',
    'monthviews' => '16',
  ),
  12 => 
  array (
    'id' => '12',
    'catid' => '6',
    'typeid' => '0',
    'title' => '辽宁海事局连发两道航行警告：渤黄海将有军事任务',
    'style' => '',
    'thumb' => '',
    'keywords' => '海事局 黄海 辽宁',
    'description' => '辽宁海事局连发两道航行警告：渤黄海将有军事任务',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=6&id=12',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1534490267',
    'updatetime' => '1540258240',
    'hitsid' => 'c-1-12',
    'views' => '14',
    'yesterdayviews' => '12',
    'dayviews' => '1',
    'weekviews' => '13',
    'monthviews' => '13',
  ),
  23 => 
  array (
    'id' => '23',
    'catid' => '6',
    'typeid' => '0',
    'title' => '喜才',
    'style' => '',
    'thumb' => 'https://timgsa.baidu.com/timg?image&amp;quality=80&amp;size=b9999_10000&amp;sec=1548489089&amp;di=ba',
    'keywords' => '喜才',
    'description' => '                         北京物资学院招生主任张喜才老师记者：感谢物资学院张喜才老师接受我们的专访，首先想   ',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=6&id=23',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1540260422',
    'updatetime' => '1540270363',
    'hitsid' => 'c-1-23',
    'views' => '6',
    'yesterdayviews' => '0',
    'dayviews' => '6',
    'weekviews' => '6',
    'monthviews' => '6',
  ),
  20 => 
  array (
    'id' => '20',
    'catid' => '6',
    'typeid' => '0',
    'title' => '在现代激烈的商业竞争中，高寿的企业可谓越来越罕见。',
    'style' => '',
    'thumb' => 'http://local.pct.com/uploadfile/2018/1023/20181023091852443.png',
    'keywords' => '高寿 越来越 商业测试',
    'description' => '在现代激烈的商业竞争中，高寿的企业可谓越来越罕见。
测试中~sorry the  number you have dialoged id busy',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=6&id=20',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1540257479',
    'updatetime' => '1550818571',
    'hitsid' => 'c-1-20',
    'views' => '8',
    'yesterdayviews' => '0',
    'dayviews' => '4',
    'weekviews' => '4',
    'monthviews' => '4',
  ),
  22 => 
  array (
    'id' => '22',
    'catid' => '6',
    'typeid' => '0',
    'title' => '小军',
    'style' => '',
    'thumb' => 'https://timgsa.baidu.com/timg?image&amp;quality=80&amp;size=b9999_10000&amp;sec=1547894396329&amp;di',
    'keywords' => '小军',
    'description' => '编者按：2015年12月15日，清华大学经济管理学院MBA教育中心主办的2015清华大学工商管理案例大赛决赛在清华大学经济管理学院进行。今年的案   ',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=6&id=22',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1540260395',
    'updatetime' => '1540261479',
    'hitsid' => 'c-1-22',
    'views' => '3',
    'yesterdayviews' => '0',
    'dayviews' => '3',
    'weekviews' => '3',
    'monthviews' => '3',
  ),
  28 => 
  array (
    'id' => '28',
    'catid' => '6',
    'typeid' => '0',
    'title' => 'new_test',
    'style' => '',
    'thumb' => 'http://local.pct.com/uploadfile/2018/1026/20181026014709759.jpg',
    'keywords' => '',
    'description' => '10月25日，清华大学在京举行签约仪式，香港嘉华集团主席及吕志和慈善基金董事吕志和博士宣布向清华大学捐赠2亿元人民币人民政协网北京10月2   ',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=6&id=28',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1540532811',
    'updatetime' => '1540532845',
    'hitsid' => 'c-1-28',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  9 => 
  array (
    'id' => '9',
    'catid' => '6',
    'typeid' => '0',
    'title' => '金正恩视察温泉设施 出现使用手机和淋雨照(图)',
    'style' => '',
    'thumb' => 'http://local.pct.com/uploadfile/2018/0817/20180817044715107.jpg',
    'keywords' => '金正 温泉 设施',
    'description' => '[环球网综合报道]据朝中社17日报道，朝鲜国务委员会委员长金正恩视察平安南道阳德郡内的温泉地区。金正恩在视察时表示，朝鲜虽有不少温泉资源，但没有像样的综合性服务基地，其还亲自',
    'posids' => '1',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=6&id=9',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1534490166',
    'updatetime' => '1550730353',
    'hitsid' => 'c-1-9',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  1 => 
  array (
    'id' => '1',
    'catid' => '6',
    'typeid' => '0',
    'title' => '习近平对首个“中国医师节”作出指示',
    'style' => '',
    'thumb' => '',
    'keywords' => '习近平 中国 医师',
    'description' => '原标题：习近平对首个“中国医师节”作出重要指示强调　　弘扬救死扶伤的人道主义精神　　不断为增进人民健康作出新贡献',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=6&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1534489772',
    'updatetime' => '1534497418',
    'hitsid' => 'c-1-1',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  4 => 
  array (
    'id' => '4',
    'catid' => '6',
    'typeid' => '0',
    'title' => '红芯浏览器致歉：宣传夸大 不应特别强调国产自主',
    'style' => '',
    'thumb' => '',
    'keywords' => '浏览器 国产',
    'description' => '原标题：红芯浏览器致歉：宣传中存在夸大，不应特别强调国产自主',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=6&id=4',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1534489953',
    'updatetime' => '1550818073',
    'hitsid' => 'c-1-4',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  3 => 
  array (
    'id' => '3',
    'catid' => '6',
    'typeid' => '0',
    'title' => '美报告：解放军为台海冲突作准备 要用最短时间取胜',
    'style' => '',
    'thumb' => '',
    'keywords' => '美报 台海 解放军',
    'description' => '在上周五，也就是8月10日，我们《出鞘》栏目发表了一篇有关于中国气垫登陆艇发展以及未来作战应用的文章。虽然新浪军事无心插柳，不过这期《出鞘》的标题图却似乎戳到了部分台湾省媒体',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=6&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1534489918',
    'updatetime' => '1534643534',
    'hitsid' => 'c-1-3',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
);
?>