<?php
return array (
  12 => 
  array (
    'id' => '12',
    'catid' => '6',
    'typeid' => '0',
    'title' => '辽宁海事局连发两道航行警告：渤黄海将有军事任务',
    'style' => '',
    'thumb' => '',
    'keywords' => '海事局 黄海 辽宁',
    'description' => '辽宁海事局连发两道航行警告：渤黄海将有军事任务',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=6&id=12',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1534490267',
    'updatetime' => '1540258240',
    'hitsid' => 'c-1-12',
    'views' => '14',
    'yesterdayviews' => '12',
    'dayviews' => '1',
    'weekviews' => '13',
    'monthviews' => '13',
  ),
  23 => 
  array (
    'id' => '23',
    'catid' => '6',
    'typeid' => '0',
    'title' => '喜才',
    'style' => '',
    'thumb' => 'file:///C:UsersADMINI~1AppDataLocalTempmsohtmlclip1�1clip_image001.jpg',
    'keywords' => '喜才',
    'description' => '                         北京物资学院招生主任张喜才老师记者：感谢物资学院张喜才老师接受我们的专访，首先想   ',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=6&id=23',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1540260422',
    'updatetime' => '1540261510',
    'hitsid' => 'c-1-23',
    'views' => '4',
    'yesterdayviews' => '0',
    'dayviews' => '4',
    'weekviews' => '4',
    'monthviews' => '4',
  ),
  20 => 
  array (
    'id' => '20',
    'catid' => '6',
    'typeid' => '0',
    'title' => '在现代激烈的商业竞争中，高寿的企业可谓越来越罕见。',
    'style' => '',
    'thumb' => 'http://local.pct.com/uploadfile/2018/1023/20181023091852443.png',
    'keywords' => '高寿 越来越 商业测试',
    'description' => '在现代激烈的商业竞争中，高寿的企业可谓越来越罕见。
测试中~sorry the  number you have dialoged id busy',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=6&id=20',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1540257479',
    'updatetime' => '1540258221',
    'hitsid' => 'c-1-20',
    'views' => '4',
    'yesterdayviews' => '0',
    'dayviews' => '4',
    'weekviews' => '4',
    'monthviews' => '4',
  ),
  22 => 
  array (
    'id' => '22',
    'catid' => '6',
    'typeid' => '0',
    'title' => '小军',
    'style' => '',
    'thumb' => 'file:///C:UsersADMINI~1AppDataLocalTempmsohtmlclip1' . "\0" . '1clip_image001.jpg',
    'keywords' => '小军',
    'description' => '编者按：2015年12月15日，清华大学经济管理学院MBA教育中心主办的2015清华大学工商管理案例大赛决赛在清华大学经济管理学院进行。今年的案   ',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=6&id=22',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1540260395',
    'updatetime' => '1540261479',
    'hitsid' => 'c-1-22',
    'views' => '3',
    'yesterdayviews' => '0',
    'dayviews' => '3',
    'weekviews' => '3',
    'monthviews' => '3',
  ),
  4 => 
  array (
    'id' => '4',
    'catid' => '6',
    'typeid' => '0',
    'title' => '红芯浏览器致歉：宣传夸大 不应特别强调国产自主',
    'style' => '',
    'thumb' => '',
    'keywords' => '浏览器 国产',
    'description' => '原标题：红芯浏览器致歉：宣传中存在夸大，不应特别强调国产自主',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=6&id=4',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1534489953',
    'updatetime' => '1534645866',
    'hitsid' => 'c-1-4',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  3 => 
  array (
    'id' => '3',
    'catid' => '6',
    'typeid' => '0',
    'title' => '美报告：解放军为台海冲突作准备 要用最短时间取胜',
    'style' => '',
    'thumb' => '',
    'keywords' => '美报 台海 解放军',
    'description' => '在上周五，也就是8月10日，我们《出鞘》栏目发表了一篇有关于中国气垫登陆艇发展以及未来作战应用的文章。虽然新浪军事无心插柳，不过这期《出鞘》的标题图却似乎戳到了部分台湾省媒体',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=6&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1534489918',
    'updatetime' => '1534643534',
    'hitsid' => 'c-1-3',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  1 => 
  array (
    'id' => '1',
    'catid' => '6',
    'typeid' => '0',
    'title' => '习近平对首个“中国医师节”作出指示',
    'style' => '',
    'thumb' => '',
    'keywords' => '习近平 中国 医师',
    'description' => '原标题：习近平对首个“中国医师节”作出重要指示强调　　弘扬救死扶伤的人道主义精神　　不断为增进人民健康作出新贡献',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=6&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1534489772',
    'updatetime' => '1534497418',
    'hitsid' => 'c-1-1',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  21 => 
  array (
    'id' => '21',
    'catid' => '6',
    'typeid' => '0',
    'title' => '（test）日后可删除',
    'style' => '',
    'thumb' => '',
    'keywords' => '（test）日后可删除',
    'description' => '　',
    'posids' => '0',
    'url' => 'https://mp.weixin.qq.com/s/IZJqQwJAc1TIdYLO1IT66g',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'phpcms',
    'inputtime' => '1540258940',
    'updatetime' => '1540258974',
    'hitsid' => 'c-1-21',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '6',
    'typeid' => '0',
    'title' => '十九届中央委员中 他是首个被处理的',
    'style' => '',
    'thumb' => '',
    'keywords' => '中央委员',
    'description' => '中共中央政治局常务委员会8月16日召开会议，听取关于吉林长春长生公司问题疫苗案件调查及有关问责情况的汇报。中共中央总书记习近平主持会议并发表重要讲话。',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=6&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1534489891',
    'updatetime' => '1534489916',
    'hitsid' => 'c-1-2',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  10 => 
  array (
    'id' => '10',
    'catid' => '6',
    'typeid' => '0',
    'title' => '外媒:美方希望中国将人民币汇率拉回贸易战前水平',
    'style' => '',
    'thumb' => '',
    'keywords' => '贸易战 美方 汇率',
    'description' => '参考消息网8月17日报道 外媒称，中国16日表示，将于8月晚些时候在华盛顿与美国举行新一轮贸易谈判，这一消息为解决令全球市场紧张不安的冲突带来一线希望。',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=6&id=10',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1534490207',
    'updatetime' => '1534490241',
    'hitsid' => 'c-1-10',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>