<?php
return array (
  12 => 
  array (
    'id' => '12',
    'catid' => '6',
    'typeid' => '0',
    'title' => '辽宁海事局连发两道航行警告：渤黄海将有军事任务',
    'style' => '',
    'thumb' => '',
    'keywords' => '海事局 黄海 辽宁',
    'description' => '辽宁海事局连发两道航行警告：渤黄海将有军事任务',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=6&id=12',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1534490267',
    'updatetime' => '1540176705',
    'hitsid' => 'c-1-12',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  1 => 
  array (
    'id' => '1',
    'catid' => '6',
    'typeid' => '0',
    'title' => '习近平对首个“中国医师节”作出指示',
    'style' => '',
    'thumb' => '',
    'keywords' => '习近平 中国 医师',
    'description' => '原标题：习近平对首个“中国医师节”作出重要指示强调　　弘扬救死扶伤的人道主义精神　　不断为增进人民健康作出新贡献',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=6&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1534489772',
    'updatetime' => '1534497418',
    'hitsid' => 'c-1-1',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  4 => 
  array (
    'id' => '4',
    'catid' => '6',
    'typeid' => '0',
    'title' => '红芯浏览器致歉：宣传夸大 不应特别强调国产自主',
    'style' => '',
    'thumb' => '',
    'keywords' => '浏览器 国产',
    'description' => '原标题：红芯浏览器致歉：宣传中存在夸大，不应特别强调国产自主',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=6&id=4',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1534489953',
    'updatetime' => '1534645866',
    'hitsid' => 'c-1-4',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  3 => 
  array (
    'id' => '3',
    'catid' => '6',
    'typeid' => '0',
    'title' => '美报告：解放军为台海冲突作准备 要用最短时间取胜',
    'style' => '',
    'thumb' => '',
    'keywords' => '美报 台海 解放军',
    'description' => '在上周五，也就是8月10日，我们《出鞘》栏目发表了一篇有关于中国气垫登陆艇发展以及未来作战应用的文章。虽然新浪军事无心插柳，不过这期《出鞘》的标题图却似乎戳到了部分台湾省媒体',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=6&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1534489918',
    'updatetime' => '1534643534',
    'hitsid' => 'c-1-3',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '6',
    'typeid' => '0',
    'title' => '十九届中央委员中 他是首个被处理的',
    'style' => '',
    'thumb' => '',
    'keywords' => '中央委员',
    'description' => '中共中央政治局常务委员会8月16日召开会议，听取关于吉林长春长生公司问题疫苗案件调查及有关问责情况的汇报。中共中央总书记习近平主持会议并发表重要讲话。',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=6&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1534489891',
    'updatetime' => '1534489916',
    'hitsid' => 'c-1-2',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  11 => 
  array (
    'id' => '11',
    'catid' => '6',
    'typeid' => '0',
    'title' => '湖南五名厅官同日被查 4人与女性有不正当性关系',
    'style' => '',
    'thumb' => '',
    'keywords' => '五名 湖南 性关系',
    'description' => '原标题：多名女下属成情人，厅官与妻子同时被捕',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=6&id=11',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1534490243',
    'updatetime' => '1534490265',
    'hitsid' => 'c-1-11',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  10 => 
  array (
    'id' => '10',
    'catid' => '6',
    'typeid' => '0',
    'title' => '外媒:美方希望中国将人民币汇率拉回贸易战前水平',
    'style' => '',
    'thumb' => '',
    'keywords' => '贸易战 美方 汇率',
    'description' => '参考消息网8月17日报道 外媒称，中国16日表示，将于8月晚些时候在华盛顿与美国举行新一轮贸易谈判，这一消息为解决令全球市场紧张不安的冲突带来一线希望。',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=6&id=10',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1534490207',
    'updatetime' => '1534490241',
    'hitsid' => 'c-1-10',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  5 => 
  array (
    'id' => '5',
    'catid' => '6',
    'typeid' => '0',
    'title' => '这家“台独”面包店喊冤?看看它在大陆做了哪些事',
    'style' => '',
    'thumb' => '',
    'keywords' => '面包店 大陆',
    'description' => '原标题：锐参考 | 这家“台独”面包店喊冤？看看这些年它在大陆做了哪些事！',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=6&id=5',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1534490046',
    'updatetime' => '1534490072',
    'hitsid' => 'c-1-5',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  6 => 
  array (
    'id' => '6',
    'catid' => '6',
    'typeid' => '0',
    'title' => '两次阅兵之后 这位将军的新职最特殊',
    'style' => '',
    'thumb' => '',
    'keywords' => '将军',
    'description' => '原标题：两次阅兵之后，这位将军的新职最特殊',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=6&id=6',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1534490074',
    'updatetime' => '1534490094',
    'hitsid' => 'c-1-6',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  7 => 
  array (
    'id' => '7',
    'catid' => '6',
    'typeid' => '0',
    'title' => '建议设生育基金还要对丁克征税?政法大学教授回应',
    'style' => '',
    'thumb' => '',
    'keywords' => '政法大学 教授 建议',
    'description' => '原标题：政法大学教授：生育基金应由国家出钱 不鼓励丁克家庭',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=6&id=7',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1534490096',
    'updatetime' => '1534490137',
    'hitsid' => 'c-1-7',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>