<?php
return array (
  1 => 
  array (
    'id' => '1',
    'catid' => '7',
    'typeid' => '0',
    'title' => '中日友好医院回应泄露艺人林更新病历：“已婚”为病历模',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '中日友好医院回应泄露艺人林更新病历：“已婚”为病历模板',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=7&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1534491938',
    'updatetime' => '1534492059',
    'systems' => 'Win2000/WinXP/Win2003',
    'copytype' => '免费版',
    'language' => '英文',
    'classtype' => '',
    'version' => '',
    'filesize' => '未知',
    'stars' => '',
    'hitsid' => 'c-2-1',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '7',
    'typeid' => '0',
    'title' => '64岁刘晓庆近照曝光 泳装出镜无惧素颜',
    'style' => '',
    'thumb' => '',
    'keywords' => '近照 刘晓庆 泳装',
    'description' => '64岁刘晓庆近照曝光 泳装出镜无惧素颜',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=7&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1534492060',
    'updatetime' => '1534492205',
    'systems' => 'Win2000/WinXP/Win2003',
    'copytype' => '免费版',
    'language' => '英文',
    'classtype' => '',
    'version' => '',
    'filesize' => '未知',
    'stars' => '',
    'hitsid' => 'c-2-2',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  3 => 
  array (
    'id' => '3',
    'catid' => '7',
    'typeid' => '0',
    'title' => '陈坤新剧《天盛长歌》开播 网剧《疯人院》好评如',
    'style' => '',
    'thumb' => '',
    'keywords' => '天盛 疯人院 新剧',
    'description' => '陈坤新剧《天盛长歌》开播 网剧《疯人院》好评如',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=7&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1534492206',
    'updatetime' => '1534492252',
    'systems' => 'Win2000/WinXP/Win2003',
    'copytype' => '免费版',
    'language' => '英文',
    'classtype' => '',
    'version' => '',
    'filesize' => '未知',
    'stars' => '',
    'hitsid' => 'c-2-3',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  4 => 
  array (
    'id' => '4',
    'catid' => '7',
    'typeid' => '0',
    'title' => '理财不慎才赚9亿？扒一扒黄晓明等明星理财的那些',
    'style' => '',
    'thumb' => '',
    'keywords' => '黄晓明 不慎 明星',
    'description' => '理财不慎才赚9亿？扒一扒黄晓明等明星理财的那些',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=7&id=4',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1534492254',
    'updatetime' => '1534492283',
    'systems' => 'Win2000/WinXP/Win2003',
    'copytype' => '免费版',
    'language' => '英文',
    'classtype' => '',
    'version' => '',
    'filesize' => '未知',
    'stars' => '',
    'hitsid' => 'c-2-4',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  5 => 
  array (
    'id' => '5',
    'catid' => '7',
    'typeid' => '0',
    'title' => '黄晓明深夜声明：未参与股票操控 是理财不慎 回',
    'style' => '',
    'thumb' => 'http://local.pct.com/uploadfile/2018/0817/thumb_110_0_20180817044349179.jpg',
    'keywords' => '黄晓明 不慎 股票',
    'description' => '黄晓明深夜声明：未参与股票操控 是理财不慎 回',
    'posids' => '1',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=7&id=5',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1534492285',
    'updatetime' => '1534492326',
    'systems' => 'Win2000/WinXP/Win2003',
    'copytype' => '免费版',
    'language' => '英文',
    'classtype' => '其他',
    'version' => '3.24',
    'filesize' => '未知',
    'stars' => '★★★★★',
    'hitsid' => 'c-2-5',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  6 => 
  array (
    'id' => '6',
    'catid' => '7',
    'typeid' => '0',
    'title' => '还记得《我叫金三顺》里的金三顺吗？她现在长这样',
    'style' => '',
    'thumb' => '',
    'keywords' => '金三顺',
    'description' => '还记得《我叫金三顺》里的金三顺吗？她现在长这样',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=7&id=6',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1534492327',
    'updatetime' => '1534492357',
    'systems' => 'Win2000/WinXP/Win2003',
    'copytype' => '免费版',
    'language' => '英文',
    'classtype' => '',
    'version' => '',
    'filesize' => '未知',
    'stars' => '',
    'hitsid' => 'c-2-6',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  7 => 
  array (
    'id' => '7',
    'catid' => '7',
    'typeid' => '0',
    'title' => '贾静雯修杰楷为咘咘庆生，大女儿梧桐妹终于露全脸',
    'style' => '',
    'thumb' => '',
    'keywords' => '贾静雯 梧桐 女儿',
    'description' => '贾静雯修杰楷为咘咘庆生，大女儿梧桐妹终于露全脸',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=7&id=7',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1534492359',
    'updatetime' => '1534492421',
    'systems' => 'Win2000/WinXP/Win2003',
    'copytype' => '免费版',
    'language' => '英文',
    'classtype' => '',
    'version' => '',
    'filesize' => '未知',
    'stars' => '',
    'hitsid' => 'c-2-7',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>