<?php
return array (
  19 => 
  array (
    'id' => '19',
    'catid' => '9',
    'typeid' => '0',
    'title' => '北京房租近两月涨500到1500 过半房源被代理垄断',
    'style' => '',
    'thumb' => 'http://local.pct.com/uploadfile/2018/0817/20180817045107391.jpg',
    'keywords' => '房租 北京 房源',
    'description' => '谁推高了房租？　侯润芳 顾志娟 赵昕 位威 樊悦池 游佳颖 陈诗怡 杨璐萍6月底7月初，生活在北京的金女士计划在公益西桥附近租一套两居室，彼时的价格在7500元左右。但出差十天回',
    'posids' => '1',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=9&id=19',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1534490848',
    'updatetime' => '1535961802',
    'hitsid' => 'c-1-19',
    'views' => '20',
    'yesterdayviews' => '0',
    'dayviews' => '3',
    'weekviews' => '3',
    'monthviews' => '3',
  ),
  13 => 
  array (
    'id' => '13',
    'catid' => '9',
    'typeid' => '0',
    'title' => '山西：禁止机关人员穿“超短裙”进入省委大院',
    'style' => '',
    'thumb' => '',
    'keywords' => '山西 超短裙 大院',
    'description' => '山西：禁止机关人员穿“超短裙”进入省委大院',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=9&id=13',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1534490489',
    'updatetime' => '1534899211',
    'hitsid' => 'c-1-13',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  14 => 
  array (
    'id' => '14',
    'catid' => '9',
    'typeid' => '0',
    'title' => '年轻人结婚率不断下降的真相来了 这组数据太准',
    'style' => '',
    'thumb' => '',
    'keywords' => '真相 年轻人 不断',
    'description' => '原标题：年轻人婚姻“真相”来了！这组数据太准…',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=9&id=14',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1534490518',
    'updatetime' => '1534490629',
    'hitsid' => 'c-1-14',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  15 => 
  array (
    'id' => '15',
    'catid' => '9',
    'typeid' => '0',
    'title' => '民政局给新人发家庭手册:女性露胳膊是作贱自己',
    'style' => '',
    'thumb' => '',
    'keywords' => '民政局 胳膊 新人',
    'description' => '15日 ，河北邯郸，网友称到复兴区民政局领结婚证，发给了她一本名为《家和万事兴》的红色小书，内容看似为“伦理道德，治家之道”，但实质为“歧视女性，挑战医学常识”。 工作人员说',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=9&id=15',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1534490631',
    'updatetime' => '1534490705',
    'hitsid' => 'c-1-15',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  16 => 
  array (
    'id' => '16',
    'catid' => '9',
    'typeid' => '0',
    'title' => '男孩被高坠花盆砸中头部致死 事发5楼暂无人居住',
    'style' => '',
    'thumb' => '',
    'keywords' => '花盆 头部 男孩',
    'description' => '原标题：湖南11岁男孩被高坠花盆砸中头部致死，事发5楼暂无人居住',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=9&id=16',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1534490707',
    'updatetime' => '1534490732',
    'hitsid' => 'c-1-16',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  17 => 
  array (
    'id' => '17',
    'catid' => '9',
    'typeid' => '0',
    'title' => '全美350多家媒体向特朗普宣战 特朗普沉默1天发声',
    'style' => '',
    'thumb' => '',
    'keywords' => '特朗普 全美 多家',
    'description' => '原标题：全美350多家媒体集体反击特朗普 特朗普回应：你们是反对党',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=9&id=17',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1534490734',
    'updatetime' => '1534490796',
    'hitsid' => 'c-1-17',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  18 => 
  array (
    'id' => '18',
    'catid' => '9',
    'typeid' => '0',
    'title' => '国务院出硬招清理奇葩证明 “你妈是你妈”证明再见',
    'style' => '',
    'thumb' => '',
    'keywords' => '国务院 奇葩',
    'description' => '2018新浪十佳银行理财师大赛火热报名中！大赛分为个人赛和团队赛，将通过线上答题、理财话题直播、线下答辩等全方位多形式选拔银行理财精英，优胜选手将有机会拿万元现金大奖、享千万',
    'posids' => '0',
    'url' => 'http://local.pct.com/index.php?m=content&c=index&a=show&catid=9&id=18',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1534490798',
    'updatetime' => '1534490846',
    'hitsid' => 'c-1-18',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>