<?php
return array (
  10 => 
  array (
    'catid' => '10',
    'siteid' => '2',
    'type' => '0',
    'modelid' => '12',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '10',
    'catname' => '游戏文章',
    'style' => '',
    'image' => '',
    'description' => '测试-游戏-文章-游戏文章',
    'parentdir' => '',
    'catdir' => 'gameArticle',
    'url' => 'http://games.pct.com/html/gameArticle/',
    'items' => '1',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"1","content_ishtml":"1","create_to_html_root":"0","template_list":"games","category_template":"category_article","list_template":"list_article","show_template":"show_article","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"1","show_ruleid":"12"}',
    'listorder' => '10',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'youxiwenzhang',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '1',
    'content_ishtml' => '1',
    'category_ruleid' => '1',
    'show_ruleid' => '12',
    'workflowid' => '',
    'isdomain' => '0',
  ),
);
?>