<?php
return array (
  1 => 
  array (
    'siteid' => '1',
    'name' => '神奇的站点',
    'dirname' => '',
    'domain' => 'http://pct.com/',
    'site_title' => 'PHPCMS演示站',
    'keywords' => 'PHPCMS演示站',
    'description' => 'PHPCMS演示站',
    'release_point' => '',
    'default_style' => 'default',
    'template' => 'default',
    'setting' => '{"upload_maxsize":"2048","upload_allowext":"jpg|jpeg|gif|bmp|png|doc|docx|xls|xlsx|ppt|pptx|pdf|txt|rar|zip|swf","watermark_enable":"1","watermark_minwidth":"300","watermark_minheight":"300","watermark_img":"statics\\/images\\/water\\/\\/mark.png","watermark_pct":"85","watermark_quality":"80","watermark_pos":"10"}',
    'uuid' => 'b2c26642-a1e7-11e8-824c-08606ef32827',
    'url' => 'http://pct.com/',
  ),
  3 => 
  array (
    'siteid' => '3',
    'name' => '游戏',
    'dirname' => 'games',
    'domain' => 'http://games.pct.com/',
    'site_title' => '游戏-测试',
    'keywords' => '游戏-keyword-测试',
    'description' => '游戏-description-测试',
    'release_point' => '',
    'default_style' => 'PandaWeb',
    'template' => 'PandaWeb',
    'setting' => '{"upload_maxsize":"2000","upload_allowext":"jpg|jpeg|gif|bmp|png|doc|docx|xls|xlsx|ppt|pptx|pdf|txt|rar|zip|swf","watermark_enable":"0","watermark_minwidth":"300","watermark_minheight":"300","watermark_img":"statics\\/images\\/water\\/http:\\/\\/local.pct.com\\/mark.gif","watermark_pct":"100","watermark_quality":"80","watermark_pos":"9"}',
    'uuid' => '',
    'url' => 'http://games.pct.com/',
  ),
  4 => 
  array (
    'siteid' => '4',
    'name' => '灰色头像',
    'dirname' => 'black',
    'domain' => 'http://black.pct.com/',
    'site_title' => '灰色头像',
    'keywords' => '主题 黑色',
    'description' => '黑色主题模板',
    'release_point' => '',
    'default_style' => 'Black',
    'template' => 'Black',
    'setting' => '{"upload_maxsize":"2000","upload_allowext":"jpg|jpeg|gif|bmp|png|doc|docx|xls|xlsx|ppt|pptx|pdf|txt|rar|zip|swf","watermark_enable":"0","watermark_minwidth":"300","watermark_minheight":"300","watermark_img":"statics\\/images\\/water\\/http:\\/\\/local.pct.com\\/mark.gif","watermark_pct":"100","watermark_quality":"80","watermark_pos":"9"}',
    'uuid' => '',
    'url' => 'http://black.pct.com/',
  ),
  5 => 
  array (
    'siteid' => '5',
    'name' => '兴宏程_本地',
    'dirname' => 'xhc',
    'domain' => 'http://xhc.pct.com/',
    'site_title' => '兴宏程_本地',
    'keywords' => '兴宏程_本地',
    'description' => '兴宏程_本地_新版_测试',
    'release_point' => '',
    'default_style' => 'xhc',
    'template' => 'xhc',
    'setting' => '{"upload_maxsize":"2000","upload_allowext":"jpg|jpeg|gif|bmp|png|doc|docx|xls|xlsx|ppt|pptx|pdf|txt|rar|zip|swf","watermark_enable":"0","watermark_minwidth":"300","watermark_minheight":"300","watermark_img":"statics\\/images\\/water\\/http:\\/\\/local.pct.com\\/mark.gif","watermark_pct":"100","watermark_quality":"80","watermark_pos":"9"}',
    'uuid' => '',
    'url' => 'http://xhc.pct.com/',
  ),
  6 => 
  array (
    'siteid' => '6',
    'name' => '克隆测试',
    'dirname' => 'clone',
    'domain' => 'http://clone.pct.com/',
    'site_title' => '克隆测试',
    'keywords' => '克隆测试',
    'description' => '克隆测试',
    'release_point' => '',
    'default_style' => 'xhc',
    'template' => 'xhc',
    'setting' => '{"upload_maxsize":"2000","upload_allowext":"jpg|jpeg|gif|bmp|png|doc|docx|xls|xlsx|ppt|pptx|pdf|txt|rar|zip|swf","watermark_enable":"0","watermark_minwidth":"300","watermark_minheight":"300","watermark_img":"http:\\/\\/local.pct.com\\/statics\\/images\\/water\\/mark.gif","watermark_pct":"100","watermark_quality":"80","watermark_pos":"9"}',
    'uuid' => '',
    'url' => 'http://clone.pct.com/',
  ),
);
?>